#!/usr/bin/env python3
"""
🔧 Environment Setup Script
Helps users create their .env file securely
"""

import os

def create_env_file():
    """Create .env file with user input"""
    print("🔧 Air Quality Monitor - Environment Setup")
    print("=" * 50)
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("⚠️  .env file already exists!")
        overwrite = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if overwrite != 'y':
            print("❌ Setup cancelled.")
            return
    
    print("\n📝 Please provide the following information:")
    print("Get your Anthropic API key from: https://console.anthropic.com/")
    
    # Get API key
    while True:
        api_key = input("\n🔑 Enter your Anthropic API key: ").strip()
        if api_key:
            break
        print("❌ API key cannot be empty!")
    
    # Get optional configurations
    cassandra_host = input("🗄️  Cassandra host (default: 127.0.0.1): ").strip() or "127.0.0.1"
    cassandra_keyspace = input("🗄️  Cassandra keyspace (default: pollution_db): ").strip() or "pollution_db"
    web_port = input("🌐 Web port (default: 7860): ").strip() or "7860"
    
    # Create .env content
    env_content = f"""# Environment Variables for Air Quality Monitor
# Auto-generated by setup_env.py

# Anthropic Claude API Key
ANTHROPIC_API_KEY={api_key}

# Database Configuration
CASSANDRA_HOSTS={cassandra_host}
CASSANDRA_KEYSPACE={cassandra_keyspace}

# Web Interface
WEB_PORT={web_port}
WEB_HOST=0.0.0.0
"""
    
    # Write .env file
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print("\n✅ .env file created successfully!")
        print("🔒 Your API key is now securely stored.")
        print("📋 Configuration:")
        print(f"   API Key: {'*' * 20}...{api_key[-4:]}")
        print(f"   Cassandra Host: {cassandra_host}")
        print(f"   Keyspace: {cassandra_keyspace}")
        print(f"   Web Port: {web_port}")
        
        print("\n🚀 You can now run: python start.py")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")

if __name__ == "__main__":
    create_env_file() 